### ISSUE TITLE
update

### ISSUE THREAD

**Issue by chen135347542093** [rovh/Set-Precise-Mesh#19]
Excuse me, can you update this plugin? 3.0 is not supported.

**Comment by rovh** [comment]
Try it now. I think it should work now

**Comment by chen135347542093** [comment]
Thanks, version 3.4 can be used, but the degree of setting Angle is not correct, there should be a bug

**Comment by chen135347542093** [comment]
Can you increase the Settings, to fix some lines or points, now when you set the values, things will be a little messy
